services:
  - type: web
    name: discord
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python sbot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
